### ISSUE TITLE
Example on how to run the containers from docker hub

### ISSUE THREAD

**Issue by shalak** [WardPearce/paaster#188]
Can we add an example on how to deploy the images from docker hub?

I'm most curious on that part, from the current `docker-compose.yaml` fie:

```
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_API_URL: "http://localhost:8888"
        # Name what appears on the website.
        VITE_NAME: "paaster"
```

The base URL of frontend service must be set during build time? How to set it for a docker hub image?

**Comment by WardPearce** [comment]
Greetings,
The yaml snippet you've provided is to do with the frontend.

> The base URL of frontend service must be set during build time? How to set it for a docker hub image?

I'm assuming your mistaking the `docker-compose.yaml` file for the `Dockerfile`, `docker-compose.yaml` isn't used during the build process for deploying to docker hub hence the 2 different images for [paaster-backend](https://hub.docker.com/r/wardpearce/paaster-backend) or [paaster-frontend](https://hub.docker.com/r/wardpearce/paaster-frontend), the `docker-compose.yaml` file should be built on your server for deploying the project.

You can use the Docker hub hosted images instead of building from git by using
```yaml
services:
  starlette:
    container_name: paaster_backend
    image: wardpearce/paaster-backend:latest
```

instead of
```yaml
services:
  starlette:
    container_name: paaster_backend
    build:
      dockerfile: ./Dockerfile
      context: ./backend
```

But you've made me notice that the example `docker-compose.yaml` should probably use the docker hub hosted images instead of building them locally, So I'll update the `docker-compose.yaml` file now. 

The `VITE_API_URL` environmental variable should be the reverse proxied URL, for example for Paaster.io I have my API container reversed proxied using Caddy at the domain `api.paaster.io`, so this value should be `https://api.paaster.io`.

Both the Frontend (Unless deploying via Vercel) & Backend should be reversed proxied using some sort of reverse proxy like Caddy, Nginx or Apache2.

Lmk if that helps or if you have any follow up questions.
