### ISSUE TITLE
Improve documentation on S3 storage and overall architecture

### ISSUE THREAD

**Issue by shalak** [WardPearce/paaster#191]
Could someone elaborate on the role and purpose of S3 storage in this system? 

We also have 'paaster_mongo' in use. Is it necessary to have these two types of data storage to run Paaster? What are they used for?

**Comment by WardPearce** [comment]
I'm open to conversations & changes around Paaster's architecture.

S3 is used for object storage, so large blocks of data (in this case encrypted pastes) can be stored and delivered effectively via a CDN. Benefits of using S3 includes data chunking, content delivery & redundancy.

Mongo DB is basically used to provide metadata of an encrypted paste. This includes paste expiration, access code storage, IV storage & owner secrets.

Mongo DB isn't designed for large data storage and would be unpractical too, Mongo DB storage isn't cheap, limited to 16 MB per document and would require loading an entire encrypted paste into memory just to access other metadata around the paste.

For example if someone uploaded a 500MBs paste, this would have to be read entirely into memory and any subsequent queries to that document would load 500MBs into memory.

**Comment by shalak** [comment]
I see. It makes sense, would be nice to have this described in README.md. I've taken a liberty of [creating a PR](https://github.com/WardPearce/paaster/pull/192).

Did you have any success with deploying Paaster with some self-hosted s3 provider? I'm trying to make the following work:

```yaml
version: '3'
services:
  paaster-backend:
    container_name: paaster-backend
    image: wardpearce/paaster-backend:latest
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      paaster_max_paste_size: 1049000
      paaster_max_iv_size: 42
      paaster_open_api: '{"title": "paaster.io", "version": "2.0.0"}'
      paaster_mongo: '{"host": "paaster-mongodb", "port": 27017, "collection": "paasterv2"}'
      paaster_s3: '{"endpoint_url": "http://paaster-minio:9000","secret_access_key": "miniosecretkey","access_key_id": "minioaccesskey","region_name": "us-east-1","bucket": "paaster","folder": "pastes","download_url": "http://paaster-minio:9000/paaster"}'
      paaster_proxy_urls: '{"frontend": "https://paaster.mydomain.net", "backend": "http://paaster-backend.mydomain.net"}'
    depends_on:
      - paaster-mongodb
      - paaster-minio
    labels:
      - "traefik.enable=true"

  paaster:
    container_name: paaster
    image: wardpearce/paaster-frontend:latest
    restart: unless-stopped
    environment:
      VITE_NAME: "paaster.mydomain.net"
      VITE_API_URL: "https://paaster-backend.mydomain.net"
    ports:
      - "8889:80"
    labels:
      - "traefik.enable=true"

  paaster-mongodb:
    image: mongo:4.4
    container_name: paaster-mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - ./paaster_data:/data/db

  paaster-minio:
    image: minio/minio
    container_name: paaster-minio
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    command: server /data
    ports:
      - "9000:9000"
```

Unfortunately, it doesn't work:

<img width="1149" alt="image" src="https://github.com/WardPearce/paaster/assets/1536554/d05b34f9-d89f-455e-8adb-9a6156101e12">


The docker [logs don't contain any errors](https://paaster.io/jgnfFax1fBte9OEiF7NCX#lMqhxE4WMYSiuHURbHtZBjy1gcXFcFjXXOGf2OW2YzU) other than:

```
paaster-backend  | 172.24.0.6:55612 - "POST /controller/paste/ZAyupYPFU1cczVuD43w73GnO0HvYVZhW HTTP/1.1" 500
```

AFAIK, in minio, the `region_name` is ignored, and `bucker`/`folder` are created on demand.

Is there a way to increase log verbosity in `paaster-backend`?

**Comment by shalak** [comment]
Side-note: I had to downgrade the mongodb to 4.4, because my CPU doesn't have AVX support.

**Comment by WardPearce** [comment]
> I see. It makes sense, would be nice to have this described in README.md. I've taken a liberty of [creating a PR](https://github.com/WardPearce/paaster/pull/192).
> 
> Did you have any success with deploying Paaster with some self-hosted s3 provider? I'm trying to make the following work:
> 
> ```yaml
> version: '3'
> services:
>   paaster-backend:
>     container_name: paaster-backend
>     image: wardpearce/paaster-backend:latest
>     restart: unless-stopped
>     ports:
>       - "8888:80"
>     environment:
>       paaster_max_paste_size: 1049000
>       paaster_max_iv_size: 42
>       paaster_open_api: '{"title": "paaster.io", "version": "2.0.0"}'
>       paaster_mongo: '{"host": "paaster-mongodb", "port": 27017, "collection": "paasterv2"}'
>       paaster_s3: '{"endpoint_url": "http://paaster-minio:9000","secret_access_key": "miniosecretkey","access_key_id": "minioaccesskey","region_name": "us-east-1","bucket": "paaster","folder": "pastes","download_url": "http://paaster-minio:9000/paaster"}'
>       paaster_proxy_urls: '{"frontend": "https://paaster.mydomain.net", "backend": "http://paaster-backend.mydomain.net"}'
>     depends_on:
>       - paaster-mongodb
>       - paaster-minio
>     labels:
>       - "traefik.enable=true"
> 
>   paaster:
>     container_name: paaster
>     image: wardpearce/paaster-frontend:latest
>     restart: unless-stopped
>     environment:
>       VITE_NAME: "paaster.mydomain.net"
>       VITE_API_URL: "https://paaster-backend.mydomain.net"
>     ports:
>       - "8889:80"
>     labels:
>       - "traefik.enable=true"
> 
>   paaster-mongodb:
>     image: mongo:4.4
>     container_name: paaster-mongodb
>     restart: unless-stopped
>     environment:
>       MONGODB_DATA_DIR: /data/db
>       MONDODB_LOG_DIR: /dev/null
>     volumes:
>       - ./paaster_data:/data/db
> 
>   paaster-minio:
>     image: minio/minio
>     container_name: paaster-minio
>     restart: unless-stopped
>     volumes:
>       - ./minio_data:/data
>     environment:
>       MINIO_ACCESS_KEY: minioaccesskey
>       MINIO_SECRET_KEY: miniosecretkey
>     command: server /data
>     ports:
>       - "9000:9000"
> ```
> 
> Unfortunately, it doesn't work:
> <img alt="image" width="1149" src="https://user-images.githubusercontent.com/1536554/246667158-d05b34f9-d89f-455e-8adb-9a6156101e12.png">
> 
> The docker [logs don't contain any errors](https://paaster.io/jgnfFax1fBte9OEiF7NCX#lMqhxE4WMYSiuHURbHtZBjy1gcXFcFjXXOGf2OW2YzU) other than:
> 
> ```
> paaster-backend  | 172.24.0.6:55612 - "POST /controller/paste/ZAyupYPFU1cczVuD43w73GnO0HvYVZhW HTTP/1.1" 500
> ```
> 
> AFAIK, in minio, the `region_name` is ignored, and `bucker`/`folder` are created on demand.
> 
> Is there a way to increase log verbosity in `paaster-backend`?

minio looks great, If you want to open a PR including instructions for optionally using minio for self hosted s3 would be appreciated.

Regrading the error, if you look at the API response, it should include what errored. But interesting it seems if the create api fails it doesn't catch it. So I'll issue a PR soon to fix that.

**Comment by WardPearce** [comment]
https://github.com/WardPearce/paaster/pull/193

Should catch why minio isn't working & provide info.

**Comment by shalak** [comment]
> minio looks great, If you want to open a PR including instructions for optionally using minio for self hosted s3 would be appreciated.

Sure, I will, once I got it working :)

The response is:
```
NoSuchBucket('An error occurred (NoSuchBucket) when calling the CreateMultipartUpload operation: The specified bucket does not exist')
```

So I fine-tuned the compose file, so a fresh `minio` container starts with a bucket. Furtunately, it's just a matter of making sure that the [data dir contains a directory with the same name as a bucket](https://github.com/minio/minio/issues/4769#issuecomment-320223201):

```yaml
  paaster-minio:
    image: minio/minio
    container_name: paaster-minio
    restart: unless-stopped
    volumes:
      - ./minio_data:/data
    environment:
      MINIO_ACCESS_KEY: minioaccesskey
      MINIO_SECRET_KEY: miniosecretkey
    entrypoint: sh
    command: -c 'mkdir -p /data/paaster && minio server /data'   # creates a dir (i.e. bucket), if not exists
    ports:
      - "9000:9000"
```

Now creating work OK, but there's a problem when trying to read the paste:
<img width="1387" alt="image" src="https://github.com/WardPearce/paaster/assets/1536554/35f0af42-5fce-4d44-b9d8-98129bf32713">

It appears, that the frontend itself is reaching out to S3 - is this an expected behavior?
