### ISSUE TITLE
Cant paste or type into paaster, no option to save/delete or anything

### ISSUE THREAD

**Issue by baudneo** [WardPearce/paaster#33]
Installed using instructions for production branch using docker. The moment I paste anything in or type 1 character the webpage freezes.

Error logs from dev tools console, 1 warning and 2 errors. 

# Warning
```
Router> Could not find an element to focus. You should always render a header for accessibility reasons, or set a custom focus element via the "useFocus" hook. If you don't want this Route or Router to manage focus, pass "primary={false}" to it.

Occurred in: <Route path="/" />
(anonymous) @ vendor.1db1a7be.js:10
(anonymous) @ vendor.1db1a7be.js:10
Promise.then (async)
hu @ vendor.1db1a7be.js:10
(anonymous) @ vendor.1db1a7be.js:10
Promise.then (async)
(anonymous) @ vendor.1db1a7be.js:10
Iu.e.$$.update @ vendor.1db1a7be.js:10
Rd @ vendor.1db1a7be.js:4
Zo @ vendor.1db1a7be.js:4
pr @ vendor.1db1a7be.js:4
dt @ index.ae4ff708.js:3
(anonymous) @ index.ae4ff708.js:3
```
# Errors
## 1
```
index.ae4ff708.js:1          GET http://localhost:8888/api/settings net::ERR_CONNECTION_REFUSED
Ge @ index.ae4ff708.js:1
r @ index.ae4ff708.js:2

```
## 2
```
Uncaught (in promise) TypeError: Failed to fetch
    at Ge (index.ae4ff708.js:1:1388)
    at HTMLTextAreaElement.r (index.ae4ff708.js:2:5058)
Ge @ index.ae4ff708.js:1
r @ index.ae4ff708.js:2
```

**Comment by WardPearce** [comment]
https://github.com/WardPearce/paaster/blob/Development/docker-compose.yml#L41
needs to be the proxied URL. E.g. for paaster.io this is set to https://api.paaster.io

**Comment by baudneo** [comment]
Found the issue, mogodb wasnt starting.

```
WARNING: MongoDB 5.0+ requires a CPU with AVX support, and your current system does not appear to have that!
  see https://jira.mongodb.org/browse/SERVER-54407
  see also https://www.mongodb.com/community/forums/t/mongodb-5-0-cpu-intel-g4650-compatibility/116610/2
  see also https://github.com/docker-library/mongo/issues/485#issuecomment-891991814
```

I have an R710 with L5640 which does not AVX instruction set. Is it possible to user a mongodb version which is compatible?

**Comment by WardPearce** [comment]
older versions should work, just specify the version in the docker compose

**Comment by baudneo** [comment]
MongoDB is working now but I get the same error regardless, none of the `docker logs` seem to hold any keys to whats going on.

- I tried with backend set to the host IP and localhost
- Tried with frontend set to the host IP and localhost
- Different variations of the 2 together.

From what I can tell the container is not setting the backend VAR because the error in DevTools console always says 
```
index.ae4ff708.js:1          GET http://localhost:8888/api/settings net::ERR_CONNECTION_REFUSED
```

After editing the docker-compose.yml file, I do a `docker-compose up -d --force-recreate`.

```
❯ nano docker-compose.yml
❯ docker-compose up -d --force-recreate
Recreating paaster_redis    ... done
Recreating paaster_frontend  ... done
Recreating paaster_mongodb  ... done
Recreating paaster_starlette ... done
❯ curl -L http://10.0.0.61:8888/api/settings
{"maxPasteSizeMb":3}#
```
So the backend is up and replying...
I am not sure how to remedy?

**Comment by WardPearce** [comment]
So you have the API exposed to port `8888`, this should be proxied with nginx (or whatever reverse proxy you prefer). Then the proxied URL should be given to the frontend via `VITE_BACKEND`. Currently you have it as `http://localhost:8888/` what won't be correct unless if you're running this all locally.

`/usr/share/nginx/html # cat /.env`
The `.env` is only used during built time of the svelte APP, this should all be configured via docker compose
[Here is how this image works](https://github.com/WardPearce/paaster/blob/Development/paaster-frontend/Dockerfile)

But seems to just be a configuration issue, make sure [FRONTEND_PROXIED](https://github.com/WardPearce/paaster/blob/Development/docker-compose.yml#L24) is the exposed proxied frontend url & that [VITE_BACKEND](https://github.com/WardPearce/paaster/blob/Development/docker-compose.yml#L41) is the exposed proxied backend url.

Might be worthwhile to just delete the 2 docker containers & start from scratch.

**Comment by baudneo** [comment]
It is only local

**Comment by WardPearce** [comment]
Tried force reload cache? `ctrl` + `f5` on Chrome, might be using a cached version of the frontend.

**Comment by baudneo** [comment]
After reloading cache the errors in chrome console change but, the same result

```
Failed to load resource: net::ERR_CONNECTION_REFUSED
index.ae4ff708.js:1          Uncaught (in promise) TypeError: Failed to fetch
    at Ge (index.ae4ff708.js:1:1388)
    at HTMLTextAreaElement.r (index.ae4ff708.js:2:5058)
```

**Comment by WardPearce** [comment]
Send me your docker compose (redact anything sensitive) & I'll have a look.

**Comment by baudneo** [comment]
```
❯ cat docker-compose.yml
version: '3'
services:
  starlette:
    container_name: paaster_starlette
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-backend
    restart: unless-stopped
    ports:
      - "8888:80"
    environment:
      MONGO_IP: "paaster_mongodb"
      MONGO_PORT: 27017
      MONGO_DB: "paaster"
      # Nano ID length https://zelark.github.io/nano-id-cc/
      NANO_ID_LEN: 21
      # Chunk size when sending a encrypted paste back to the client.
      READ_CHUNK: 1024
      # This is the max paste size of the encrypted data.
      MAX_PASTE_SIZE_MB: 3
      REDIS_HOST: "paaster_redis"
      REDIS_PORT: 6379
      # Proxied Frontend URL.
      FRONTEND_PROXIED: "http://10.0.0.61:8889"
    volumes:
      # If you change 'SAVE_PATH' this needs to be changed,
      # changing 'SAVE_PATH' is not recommended.
      - appdata:/app/pastes
    depends_on:
      - mongodb
    networks:
      - backend

  vite:
    container_name: paaster_frontend
    build:
      dockerfile: ./Dockerfile
      context: ./paaster-frontend
      args:
        # Proxied backend URL, NO TRAILING SLASH!
        VITE_BACKEND: "http://10.0.0.61:8888"
        # Name what appears on the website.
        VITE_NAME: "paaster"
    restart: unless-stopped
    ports:
      - "8889:80"

  redis:
    container_name: paaster_redis
    image: redis
    volumes:
      - redis:/data
    networks:
      - backend

  mongodb:
    image: mongo:4.4.6
    container_name: paaster_mongodb
    restart: unless-stopped
    environment:
      MONGODB_DATA_DIR: /data/db
      MONDODB_LOG_DIR: /dev/null
    volumes:
      - mongodbdata:/data/db
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis:
    driver: local
  mongodbdata:
    driver: local
  appdata:
    driver: local

```
